name: CI

on: [push, workflow_dispatch]

jobs:
  setup:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 22.x
          cache: 'yarn'
      - uses: actions/cache@v4
        id: yarn-cache
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: Install packages
        if: steps.yarn-cache.outputs.cache-hit != 'true'
        run: yarn install --immutable

  check:
    runs-on: ubuntu-latest
    needs: setup
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: lint
        run: yarn lint
      - name: solhint
        run: yarn workspace contract solhint
      - name: format
        run: yarn prettier:check

  contract-test:
    runs-on: ubuntu-latest
    needs: [setup, check]
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-${{ hashFiles('**/yarn.lock') }}
      - name: integration_test
        run: yarn workspace contract test

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
